/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Attributes { 
    endurance?: number;
    strength?: number;
    dexterity?: number;
    wisdom?: number;
    intelligence?: number;
    defense?: number;
    luck?: number;
    enduranceGrowth?: number;
    strengthGrowth?: number;
    dexterityGrowth?: number;
    wisdomGrowth?: number;
    intelligenceGrowth?: number;
    defenseGrowth?: number;
    luckGrowth?: number;
}

