/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttributeBonus { 
    statusName?: string;
    statusIcon?: string;
    bonus?: number;
    attribute?: AttributeBonus.AttributeEnum;
}
export namespace AttributeBonus {
    export type AttributeEnum = 'Strength' | 'Endurance' | 'Dexterity' | 'Wisdom' | 'Intelligence' | 'Defense' | 'Luck' | 'All';
    export const AttributeEnum = {
        Strength: 'Strength' as AttributeEnum,
        Endurance: 'Endurance' as AttributeEnum,
        Dexterity: 'Dexterity' as AttributeEnum,
        Wisdom: 'Wisdom' as AttributeEnum,
        Intelligence: 'Intelligence' as AttributeEnum,
        Defense: 'Defense' as AttributeEnum,
        Luck: 'Luck' as AttributeEnum,
        All: 'All' as AttributeEnum
    };
}


