/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Skill } from './skill';
import { Equipment } from './equipment';
import { Attributes } from './attributes';
import { ClassBonus } from './classBonus';
import { Weapon } from './weapon';


export interface CharacterClass { 
    id?: string;
    name?: string;
    description?: string;
    iconName?: string;
    lore?: string;
    humanPlayable?: boolean;
    energyType?: CharacterClass.EnergyTypeEnum;
    attributes?: Attributes;
    startingMainhand?: string;
    startingOffhand?: string;
    startingHelmet?: string;
    startingChest?: string;
    startingGloves?: string;
    startingPants?: string;
    startingBoots?: string;
    startingRing1?: string;
    startingRing2?: string;
    startingNeck?: string;
    bonuses?: Array<ClassBonus>;
    skills?: Array<string>;
    skillInstances?: Array<Skill>;
    startingMainhandInstance?: Weapon;
    startingOffhandInstance?: Weapon;
    startingHelmetInstance?: Equipment;
    startingChestInstance?: Equipment;
    startingGlovesInstance?: Equipment;
    startingPantsInstance?: Equipment;
    startingBootsInstance?: Equipment;
    startingRing1Instance?: Equipment;
    startingRing2Instance?: Equipment;
    startingNeckInstance?: Equipment;
}
export namespace CharacterClass {
    export type EnergyTypeEnum = 'Rage' | 'Focus' | 'Mana';
    export const EnergyTypeEnum = {
        Rage: 'Rage' as EnergyTypeEnum,
        Focus: 'Focus' as EnergyTypeEnum,
        Mana: 'Mana' as EnergyTypeEnum
    };
}


