/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CombatSkillBonus { 
    statusName?: string;
    statusIcon?: string;
    bonus?: number;
    skill?: CombatSkillBonus.SkillEnum;
}
export namespace CombatSkillBonus {
    export type SkillEnum = 'Dodge' | 'Critical' | 'Block' | 'Parry' | 'Spellpower' | 'Healpower';
    export const SkillEnum = {
        Dodge: 'Dodge' as SkillEnum,
        Critical: 'Critical' as SkillEnum,
        Block: 'Block' as SkillEnum,
        Parry: 'Parry' as SkillEnum,
        Spellpower: 'Spellpower' as SkillEnum,
        Healpower: 'Healpower' as SkillEnum
    };
}


