/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeBonus } from './attributeBonus';
import { CombatSkillBonus } from './combatSkillBonus';


export interface Consumable { 
    id?: string;
    name?: string;
    description?: string;
    iconName?: string;
    value?: number;
    rarity?: Consumable.RarityEnum;
    duringBattle?: boolean;
    fromInventory?: boolean;
    combatSkillModifiers?: Array<CombatSkillBonus>;
    attributeModifiers?: Array<AttributeBonus>;
    durationRounds?: number;
    healthRestored?: number;
    atkResourceRestored?: number;
    resourceType?: Consumable.ResourceTypeEnum;
}
export namespace Consumable {
    export type RarityEnum = 'COMMON' | 'UNCOMMON' | 'RARE' | 'EPIC' | 'LEGENDARY' | 'ARTIFACT';
    export const RarityEnum = {
        Common: 'COMMON' as RarityEnum,
        Uncommon: 'UNCOMMON' as RarityEnum,
        Rare: 'RARE' as RarityEnum,
        Epic: 'EPIC' as RarityEnum,
        Legendary: 'LEGENDARY' as RarityEnum,
        Artifact: 'ARTIFACT' as RarityEnum
    };
    export type ResourceTypeEnum = 'Rage' | 'Focus' | 'Mana';
    export const ResourceTypeEnum = {
        Rage: 'Rage' as ResourceTypeEnum,
        Focus: 'Focus' as ResourceTypeEnum,
        Mana: 'Mana' as ResourceTypeEnum
    };
}


