/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeBonus } from './attributeBonus';
import { CombatSkillBonus } from './combatSkillBonus';
import { AttackResourceBonus } from './attackResourceBonus';
import { SecondarySkillBonus } from './secondarySkillBonus';


export interface Equipment { 
    id?: string;
    name?: string;
    description?: string;
    iconName?: string;
    value?: number;
    rarity?: Equipment.RarityEnum;
    skillBonuses?: Array<CombatSkillBonus>;
    attributeBonuses?: Array<AttributeBonus>;
    secondarySkillBonuses?: Array<SecondarySkillBonus>;
    atkResourceBonuses?: Array<AttackResourceBonus>;
    classExclusive?: string;
    raceExclusive?: string;
    type?: Equipment.TypeEnum;
    armor?: number;
}
export namespace Equipment {
    export type RarityEnum = 'COMMON' | 'UNCOMMON' | 'RARE' | 'EPIC' | 'LEGENDARY' | 'ARTIFACT';
    export const RarityEnum = {
        Common: 'COMMON' as RarityEnum,
        Uncommon: 'UNCOMMON' as RarityEnum,
        Rare: 'RARE' as RarityEnum,
        Epic: 'EPIC' as RarityEnum,
        Legendary: 'LEGENDARY' as RarityEnum,
        Artifact: 'ARTIFACT' as RarityEnum
    };
    export type TypeEnum = 'HELMET' | 'CHEST' | 'GLOVES' | 'PANTS' | 'BOOTS' | 'RING' | 'NECK';
    export const TypeEnum = {
        Helmet: 'HELMET' as TypeEnum,
        Chest: 'CHEST' as TypeEnum,
        Gloves: 'GLOVES' as TypeEnum,
        Pants: 'PANTS' as TypeEnum,
        Boots: 'BOOTS' as TypeEnum,
        Ring: 'RING' as TypeEnum,
        Neck: 'NECK' as TypeEnum
    };
}


