/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Equipment } from './equipment';
import { Race } from './race';
import { CharacterClass } from './characterClass';
import { Weapon } from './weapon';


export interface HostileNPC { 
    id?: string;
    name?: string;
    description?: string;
    iconName?: string;
    raceId?: string;
    classId?: string;
    unique?: boolean;
    level?: number;
    mainhand?: string;
    offhand?: string;
    helmet?: string;
    chest?: string;
    gloves?: string;
    pants?: string;
    boots?: string;
    ring1?: string;
    ring2?: string;
    neck?: string;
    loottable?: { [key: string]: number; };
    minimumGold?: number;
    maximumGold?: number;
    characterClass?: CharacterClass;
    race?: Race;
    mainhandInstance?: Weapon;
    offhandInstance?: Weapon;
    helmetInstance?: Equipment;
    gloveInstance?: Equipment;
    chestInstance?: Equipment;
    pantsInstance?: Equipment;
    bootsInstance?: Equipment;
    ring1Instance?: Equipment;
    ring2Instance?: Equipment;
    neckInstance?: Equipment;
}

