/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RacialBonus } from './racialBonus';


export interface Race { 
    id?: string;
    name?: string;
    description?: string;
    iconName?: string;
    lore?: string;
    startingLocationId?: string;
    humanPlayable?: boolean;
    bonuses?: Array<RacialBonus>;
}

