/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RacialBonus { 
    id?: string;
    name?: string;
    description?: string;
    iconName?: string;
    attribute?: RacialBonus.AttributeEnum;
    weaponType?: RacialBonus.WeaponTypeEnum;
    combatSkill?: RacialBonus.CombatSkillEnum;
    secondarySkill?: RacialBonus.SecondarySkillEnum;
    modifier?: number;
}
export namespace RacialBonus {
    export type AttributeEnum = 'Strength' | 'Endurance' | 'Dexterity' | 'Wisdom' | 'Intelligence' | 'Defense' | 'Luck' | 'All';
    export const AttributeEnum = {
        Strength: 'Strength' as AttributeEnum,
        Endurance: 'Endurance' as AttributeEnum,
        Dexterity: 'Dexterity' as AttributeEnum,
        Wisdom: 'Wisdom' as AttributeEnum,
        Intelligence: 'Intelligence' as AttributeEnum,
        Defense: 'Defense' as AttributeEnum,
        Luck: 'Luck' as AttributeEnum,
        All: 'All' as AttributeEnum
    };
    export type WeaponTypeEnum = 'None' | 'Sword' | 'Axe' | 'Dagger' | 'Polearm' | 'Greatsword' | 'Greataxe' | 'Bow' | 'Crossbow' | 'Staff' | 'Wand' | 'Shield';
    export const WeaponTypeEnum = {
        None: 'None' as WeaponTypeEnum,
        Sword: 'Sword' as WeaponTypeEnum,
        Axe: 'Axe' as WeaponTypeEnum,
        Dagger: 'Dagger' as WeaponTypeEnum,
        Polearm: 'Polearm' as WeaponTypeEnum,
        Greatsword: 'Greatsword' as WeaponTypeEnum,
        Greataxe: 'Greataxe' as WeaponTypeEnum,
        Bow: 'Bow' as WeaponTypeEnum,
        Crossbow: 'Crossbow' as WeaponTypeEnum,
        Staff: 'Staff' as WeaponTypeEnum,
        Wand: 'Wand' as WeaponTypeEnum,
        Shield: 'Shield' as WeaponTypeEnum
    };
    export type CombatSkillEnum = 'Dodge' | 'Critical' | 'Block' | 'Parry' | 'Spellpower' | 'Healpower';
    export const CombatSkillEnum = {
        Dodge: 'Dodge' as CombatSkillEnum,
        Critical: 'Critical' as CombatSkillEnum,
        Block: 'Block' as CombatSkillEnum,
        Parry: 'Parry' as CombatSkillEnum,
        Spellpower: 'Spellpower' as CombatSkillEnum,
        Healpower: 'Healpower' as CombatSkillEnum
    };
    export type SecondarySkillEnum = 'secondary.skills.woodcutting' | 'secondary.skills.fishing' | 'secondary.skills.mining' | 'secondary.skills.alchemy' | 'secondary.skills.enchanting';
    export const SecondarySkillEnum = {
        Woodcutting: 'secondary.skills.woodcutting' as SecondarySkillEnum,
        Fishing: 'secondary.skills.fishing' as SecondarySkillEnum,
        Mining: 'secondary.skills.mining' as SecondarySkillEnum,
        Alchemy: 'secondary.skills.alchemy' as SecondarySkillEnum,
        Enchanting: 'secondary.skills.enchanting' as SecondarySkillEnum
    };
}


