/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SecondarySkillBonus { 
    skill?: SecondarySkillBonus.SkillEnum;
    bonus?: number;
}
export namespace SecondarySkillBonus {
    export type SkillEnum = 'secondary.skills.woodcutting' | 'secondary.skills.fishing' | 'secondary.skills.mining' | 'secondary.skills.alchemy' | 'secondary.skills.enchanting';
    export const SkillEnum = {
        Woodcutting: 'secondary.skills.woodcutting' as SkillEnum,
        Fishing: 'secondary.skills.fishing' as SkillEnum,
        Mining: 'secondary.skills.mining' as SkillEnum,
        Alchemy: 'secondary.skills.alchemy' as SkillEnum,
        Enchanting: 'secondary.skills.enchanting' as SkillEnum
    };
}


