/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SkillRequirement } from './skillRequirement';
import { StatusEffect } from './statusEffect';
import { SkillRank } from './skillRank';


export interface Skill { 
    id?: string;
    name?: string;
    description?: string;
    iconName?: string;
    iconId?: string;
    attribute?: Skill.AttributeEnum;
    type?: Skill.TypeEnum;
    targetType?: Skill.TargetTypeEnum;
    weaponModifier?: Skill.WeaponModifierEnum;
    minDamage?: number;
    maxDamage?: number;
    costOfExecution?: number;
    preparationRounds?: number;
    ranks?: Array<SkillRank>;
    requirements?: Array<SkillRequirement>;
    statusEffects?: Array<StatusEffect>;
}
export namespace Skill {
    export type AttributeEnum = 'Strength' | 'Endurance' | 'Dexterity' | 'Wisdom' | 'Intelligence' | 'Defense' | 'Luck' | 'All';
    export const AttributeEnum = {
        Strength: 'Strength' as AttributeEnum,
        Endurance: 'Endurance' as AttributeEnum,
        Dexterity: 'Dexterity' as AttributeEnum,
        Wisdom: 'Wisdom' as AttributeEnum,
        Intelligence: 'Intelligence' as AttributeEnum,
        Defense: 'Defense' as AttributeEnum,
        Luck: 'Luck' as AttributeEnum,
        All: 'All' as AttributeEnum
    };
    export type TypeEnum = 'OFFENSIVE' | 'DEFENSIVE';
    export const TypeEnum = {
        Offensive: 'OFFENSIVE' as TypeEnum,
        Defensive: 'DEFENSIVE' as TypeEnum
    };
    export type TargetTypeEnum = 'ENEMY' | 'FRIEND' | 'OWN' | 'AREA';
    export const TargetTypeEnum = {
        Enemy: 'ENEMY' as TargetTypeEnum,
        Friend: 'FRIEND' as TargetTypeEnum,
        Own: 'OWN' as TargetTypeEnum,
        Area: 'AREA' as TargetTypeEnum
    };
    export type WeaponModifierEnum = 'Mainhand' | 'Offhand' | 'None';
    export const WeaponModifierEnum = {
        Mainhand: 'Mainhand' as WeaponModifierEnum,
        Offhand: 'Offhand' as WeaponModifierEnum,
        None: 'None' as WeaponModifierEnum
    };
}


