/**
 * FantasyUnlimited API
 * Fantasy Unlimited - REST API Description
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeBonus } from './attributeBonus';
import { CombatSkillBonus } from './combatSkillBonus';
import { AttackResourceBonus } from './attackResourceBonus';
import { SecondarySkillBonus } from './secondarySkillBonus';


export interface Weapon { 
    id?: string;
    name?: string;
    description?: string;
    iconName?: string;
    value?: number;
    rarity?: Weapon.RarityEnum;
    skillBonuses?: Array<CombatSkillBonus>;
    attributeBonuses?: Array<AttributeBonus>;
    secondarySkillBonuses?: Array<SecondarySkillBonus>;
    atkResourceBonuses?: Array<AttackResourceBonus>;
    classExclusive?: string;
    raceExclusive?: string;
    type?: Weapon.TypeEnum;
    hand?: Weapon.HandEnum;
    minDamage?: number;
    maxDamage?: number;
}
export namespace Weapon {
    export type RarityEnum = 'COMMON' | 'UNCOMMON' | 'RARE' | 'EPIC' | 'LEGENDARY' | 'ARTIFACT';
    export const RarityEnum = {
        Common: 'COMMON' as RarityEnum,
        Uncommon: 'UNCOMMON' as RarityEnum,
        Rare: 'RARE' as RarityEnum,
        Epic: 'EPIC' as RarityEnum,
        Legendary: 'LEGENDARY' as RarityEnum,
        Artifact: 'ARTIFACT' as RarityEnum
    };
    export type TypeEnum = 'None' | 'Sword' | 'Axe' | 'Dagger' | 'Polearm' | 'Greatsword' | 'Greataxe' | 'Bow' | 'Crossbow' | 'Staff' | 'Wand' | 'Shield';
    export const TypeEnum = {
        None: 'None' as TypeEnum,
        Sword: 'Sword' as TypeEnum,
        Axe: 'Axe' as TypeEnum,
        Dagger: 'Dagger' as TypeEnum,
        Polearm: 'Polearm' as TypeEnum,
        Greatsword: 'Greatsword' as TypeEnum,
        Greataxe: 'Greataxe' as TypeEnum,
        Bow: 'Bow' as TypeEnum,
        Crossbow: 'Crossbow' as TypeEnum,
        Staff: 'Staff' as TypeEnum,
        Wand: 'Wand' as TypeEnum,
        Shield: 'Shield' as TypeEnum
    };
    export type HandEnum = 'LEFT' | 'RIGHT' | 'BOTH' | 'TWOHANDED';
    export const HandEnum = {
        Left: 'LEFT' as HandEnum,
        Right: 'RIGHT' as HandEnum,
        Both: 'BOTH' as HandEnum,
        Twohanded: 'TWOHANDED' as HandEnum
    };
}


